bookmyhotel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),

    path('auth/', include('myauth.urls')),

    path('support/', include('support.urls')),

    path('hotels/', include('hotels.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [
    path('', views.hotel_list, name='hotels'),
    
    path('<str:hotel_id>/', views.hotel_detail, name='hotel-detail'),

    path('<str:hotel_id>/submit-rating/', views.submit_rating, name='submit-rating'),

    path('rooms/<str:hotel_room_id>/', views.hotel_room_detail, name='hotel-room-detail'),

    path('rooms/<str:hotel_room_id>/book-room/', views.book_room, name='book-room'),
]

myauth/urls.py
from django.urls import path, reverse_lazy
from . import views
from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as authView

app_name = 'myauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

    path('login/', authView.LoginView.as_view(
        template_name = 'myauth/login_form.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authView.LogoutView.as_view(), name='logout'),

    path('password-reset/', authView.PasswordResetView.as_view(
        template_name='myauth/password_reset.html',
        email_template_name='myauth/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('myauth:password_reset_done')
    ), name='password_reset'),

    path('password-reset-done/', authView.PasswordResetDoneView.as_view(
        template_name='myauth/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', authView.PasswordResetConfirmView.as_view(
        template_name='myauth/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('myauth:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset-complete/', authView.PasswordResetCompleteView.as_view(
        template_name='myauth/password_reset_complete.html'
    ), name='password_reset_complete'),
]

support/urls.py
from django.urls import path

from . import views

app_name = 'support'

urlpatterns = [
    path('create-room/<str:room_id>/', views.create_room, name='create-room'),

    path('admin/', views.admin, name='admin'),

    path('add-user/', views.add_user, name='add-user'),

    path('edit-user/<str:id>/', views.edit_user, name='edit-user'),

    path('room/<str:room_id>/', views.room, name='room'),

    path('delete-room/<str:room_id>/', views.delete_room, name='delete-room'),


]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, 'core/home.html', {
        'title': 'Home',
        
    })

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}  {% endblock %} | BookMyHotel</title>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

        <script src="https://cdn.tailwindcss.com"></script>
        {% block style %}
        {% endblock %}
    </head>

    <body class="w-screen text-white bg-gradient-to-bl from-slate-800 to-gray-600">

        <div class="p-2">

            <nav class="w-4/5 mx-auto mt-2 px-3 py-3 flex justify-between items-center rounded-full shadow-2xl bg-gradient-to-bl from-gray-700 to-slate-800">
                
                <div class="flex justify-start items-center">
                    <img src="/media/logo.png" alt="logo" class="w-10 h-10">
                    <a href="{% url 'core:home' %}"  class="text-xl text-slate-400 font-semibold">BookMyHotel</a>
                </div>    

                <div class="flex items-center space-x-4">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'myauth:logout' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Logout</a>
                    {% else %}
                        <a href="{% url 'myauth:signup' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Signup</a>
                        <a href="{% url 'myauth:login' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Login</a>
                    {% endif %}

                    {% if request.user.is_staff %}
                        <a href="{% url 'support:admin' %}" class="inline-block px-3 py-2 text-sm bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Admin</a>
                    {% endif %}
                </div>
            </nav>

            {% if messages %}
                <div class="message w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            
        </div>

        <main class="max-w-6xl mx-auto p-6">
            {% block content %}

            {% endblock %}

            {% if not request.user.is_staff %}
                {% include 'support/partials/bubble_chat.html' %}
            {% endif %}
        </main>

        <footer class="w-full py-6 px-6 bottom-0 bg-gray-600 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Book My Hotel</p>
        </footer>

        {% if request.user.is_authenticated %}

            {{request.user.name|json_script:'user_name'}}
            {{request.user.id|json_script:'user_id'}}

        {% endif %}


        {% block scripts %}

        {% endblock %}


        {% if not request.user.is_staff %}
            <script src="{% static 'js/main.js' %}"></script>
        {% endif %}
        
    </body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}


{% block title %} {{title}} {% endblock %}


{% block content %} 
<div class="flex flex-col gap-8 items-center">
    <h1 class="text-center text-2xl text-slate-400 font-semibold mt-6 mb-6">Your one-place stop to book your perfect hotel for your vacation!!</h1>

    <img src="/media/logo.png" alt="logo" class="h-96">

    <div class="flex justify-center items-center">
        <a href="{% url 'hotels:hotels' %}" class="px-4 py-2 mt-4 rounded-xl bg-slate-600 shadow-2xl hover:bg-slate-800 transition ease-in-out duration-300">View Hotels</a>
    </div>
</div>
{% endblock %}