bookmyhotel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),

    path('auth/', include('myauth.urls')),

    path('support/', include('support.urls')),

    path('hotels/', include('hotels.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [
    path('', views.hotel_list, name='hotels'),
    
    path('<str:hotel_id>/', views.hotel_detail, name='hotel-detail'),

    path('<str:hotel_id>/submit-rating/', views.submit_rating, name='submit-rating'),

    path('rooms/<str:hotel_room_id>/', views.hotel_room_detail, name='hotel-room-detail'),

    path('rooms/<str:hotel_room_id>/book-room/', views.book_room, name='book-room'),
]

hotels/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from myauth.models import User

import uuid

# Create your models here.
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LocationType(models.TextChoices):
    URBAN = 'UR', 'Urban'
    AIRPORT = 'AP', 'Airport'
    RESORT = 'RE', 'Resort'
    MOUNTAIN = 'MT', 'Mountain'
    BEACHFRONT = 'BF', 'Beachfront'
    BOUTIQUE = 'BO', 'Boutique'
    ECO = 'EC', 'Eco'
    HIGHWAY = 'HW', 'Highway'
    CASINO = 'CA', 'Casino'


class RoomType(models.TextChoices):
    STANDARD = 'ST', 'Standard'
    DELUXE = 'DX', 'Deluxe'
    SUITE = 'SU', 'Suit'
    FAMILY = 'FR', 'Family'


class Amenity(BaseModel):
    amenity_name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['created_at',]

    def __str__(self):
        return self.amenity_name
    

# Hotel related models    

class Hotel(BaseModel):
    hotel_name = models.CharField(max_length=255)
    location = models.CharField(max_length=255, blank=True, null=True)
    amenities = models.ManyToManyField(Amenity, blank=True)
    location_type = models.CharField(max_length=2, choices=LocationType.choices, default=LocationType.URBAN,)

    # latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    # longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    def get_lowest_room_price(self):
        return self.rooms.order_by('price').first().price if self.rooms.exists() else None
    
    def get_average_rating(self):
        ratings = self.ratings.all()

        if not ratings:
            return None
        
        total = sum(rating.average_rating() for rating in ratings)
        count = ratings.count()

        return round(total / count, 2)

    def __str__(self):
        return self.hotel_name
    
class HotelImage(BaseModel):
    hotel = models.ForeignKey(Hotel, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='hotel_images')

    def __str__(self):
        return f"Image for {self.hotel.hotel_name}"
    


# Hotel-room related models    

class HotelRoom(BaseModel):
    hotel = models.ForeignKey(Hotel, related_name='rooms', on_delete=models.CASCADE)
    room_number = models.IntegerField(unique=True)
    room_type = models.CharField(max_length=2, choices=RoomType.choices, default=RoomType.STANDARD)
    price = models.FloatField()
    description = models.TextField(blank=True, null=True)

    def is_booked(self, check_date):
        return self.bookings.filter(start_date__lte=check_date, end_date__gte=check_date).exists()
    
    def get_average_rating(self):
        ratings = self.ratings.all()

        if not ratings:
            return None
        
        total = sum(rating.average_rating() for rating in ratings)
        count = ratings.count()

        return round(total / count, 2)

    def __str__(self):
        return f'{self.room_number} at {self.hotel.hotel_name}'
    
class HotelRoomImage(BaseModel):
    hotel_room = models.ForeignKey(HotelRoom, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='hotel_room_images')

    def __str__(self):
        return f"Image for room {self.hotel_room.room_number} at {self.hotel_room.hotel.hotel_name}"
    

# Booking related models

class Booking(BaseModel):
    room = models.ForeignKey(HotelRoom, related_name='bookings', blank=True, null=True, on_delete=models.SET_NULL)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'Booking for {self.room.room_number} at {self.room.hotel.hotel_name} from {self.start_date} to {self.end_date}'
    

# Rating related models

class Rating(models.Model):
    hotel = models.ForeignKey(Hotel, related_name='ratings', blank=True, null=True, on_delete=models.CASCADE)
    room = models.ForeignKey(HotelRoom, related_name='ratings', blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='ratings', blank=True, null=True, on_delete=models.SET_NULL)
    cleanliness = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    service = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    location = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    amenities = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    room_quality = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def average_rating(self):
        total = self.cleanliness + self.service + self.location + self.amenities + self.room_quality
        return round(total / 5, 2)
    
    def __str__(self):
        return f'Rating {self.average_rating()} for hotel {self.hotel.hotel_name} by {self.user.name}'



    

hotels/forms.py
from django import forms

from .models import Rating, Amenity, LocationType

from django.core.exceptions import ValidationError
from datetime import date

BOOK_ROOM_INPUT_CLASSES = 'w-full mb-2 py-1 px-3 rounded-xl bg-gray-400 text-gray-800 border'
INPUT_CLASSES = 'w-full px-3 rounded-lg bg-gray-400 text-gray-800 border'


class BookRoomForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'Enter your check-in date...',
        'class': BOOK_ROOM_INPUT_CLASSES
    }))

    end_date = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'Enter your check-out date...',
        'class': BOOK_ROOM_INPUT_CLASSES
    }))

    def clean(self):
        cleaned_data = super().clean()
        check_in = cleaned_data.get('start_date')
        check_out = cleaned_data.get('end_date')

        if check_in and check_out:
            if check_in < date.today():
                raise ValidationError('The check-in date cannot be in the past.')
            
            if check_out <= check_in:
                raise ValidationError("Check-out date must be after check-in date.")
            
        return cleaned_data
    

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('cleanliness', 'service', 'location', 'amenities', 'room_quality', 'comment')
        widgets = {
            'cleanliness': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'service': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'location': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'amenities': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'room_quality': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'comment': forms.Textarea(attrs={
                'class': 'w-full h-[150px] px-3 py-2 rounded-lg bg-gray-400 text-gray-800 border',
                'placeholder': 'Add a comment. Thank you...',
            }),
        }

    def clean(self):
        clean_data = super().clean()
        for field_name in ['cleanliness', 'service', 'location', 'amenities', 'room_quality']:
            rating = clean_data.get(field_name)
            if rating is not None and (rating < 1 or rating > 5):
                self.add_error(field_name, forms.ValidationError(f"{field_name.capitalize()} rating must be between 0 and 5."))


class HotelFilterForm(forms.Form):
    amenities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(),
        widget = forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required = False
    )

    location_types = forms.MultipleChoiceField(
        choices=LocationType.choices,
        widget=forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required=False,
        label="Location Types"
    )

hotels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from collections import defaultdict
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Q
from django.db.models import Count

from .forms import BookRoomForm, RatingForm, HotelFilterForm
from .models import Booking


from datetime import datetime, timedelta
from .models import Hotel, HotelRoom

# Create your views here.

def generate_availability_calendar(hotel_room):
    # Find out the last day of the current month
    today = datetime.today()
    next_month = today.replace(day=28) + timedelta(days=4)  # this will never fail
    last_day_of_month = next_month - timedelta(days=next_month.day)

    # Generate a list of all dates in the current month
    date_list = [today.replace(day=x) for x in range(1, last_day_of_month.day + 1)]

    # Use the is_booked method to determine room availability for each date
    availability = {date: not hotel_room.is_booked(date) for date in date_list}

    # Creating weeks for the calendar
    availability_calendar = defaultdict(lambda: [None] * 7)  # Default to None for days
        
    for date, is_available in availability.items():
        # .weekday() returns the day of the week as an integer (Monday is 0, Sunday is 6)
        availability_calendar[date.isocalendar()[1] - today.isocalendar()[1]][date.weekday()] = (date.day, 'Available' if is_available else 'Booked')

    # for week in sorted(availability_calendar):
    #     print("Week {}: {}".format(week, availability_calendar[week]))

    return dict(availability_calendar)  # Convert defaultdict to dict for the template


def hotel_list(request):
    hotels = Hotel.objects.all()
    query = request.GET.get('query', '')
    form = HotelFilterForm(request.GET)

    if form.is_valid():
        amenities = form.cleaned_data['amenities']
        location_types = form.cleaned_data['location_types']

        if amenities:
            # Start with all hotels, then narrow down by those that have each amenity.
            for amenity in amenities:
                hotels = hotels.filter(amenities=amenity)
            # Make sure that the resulting hotels are distinct
            hotels = hotels.distinct()

        if location_types:
            location_based_hotels = []
            for location_type in location_types:
                location_based_hotels += hotels.filter(location_type=location_type)
            hotels = location_based_hotels

    if query:
        hotels = hotels.filter(hotel_name__icontains = query)

    return render(request, 'hotels/hotel_list.html', {
        'title': 'Hotels',
        'hotels': hotels,
        'query': query,
        'hotel_filter_form': form,
    })

def hotel_detail(request, hotel_id):
    hotel = Hotel.objects.get(id=hotel_id)
    rating_form = RatingForm()
    ratings = hotel.ratings.all().order_by('-created_at')

    return render(request, 'hotels/hotel_detail.html', {
        'title': hotel.hotel_name,
        'hotel': hotel,
        'rating_form': rating_form,
        'ratings': ratings,
    })


def hotel_room_detail(request, hotel_room_id):
    hotel_room = get_object_or_404(HotelRoom, id=hotel_room_id)
    availability_calendar = generate_availability_calendar(hotel_room)
    booking_form = BookRoomForm()

    return render(request, 'hotels/room_detail.html', {
        'title': f'{hotel_room.hotel.hotel_name}',
        'hotel_room': hotel_room,
        'availability_calendar': availability_calendar,
        'booking_form': booking_form,
    })


@login_required
def book_room(request, hotel_room_id):
    hotel_room = get_object_or_404(HotelRoom, id=hotel_room_id)
    availability_calendar = generate_availability_calendar(hotel_room)
    if request.method == 'POST':
        form = BookRoomForm(request.POST)
        if form.is_valid():
            check_in = form.cleaned_data['start_date']
            check_out = form.cleaned_data['end_date']

            date = check_in
            while date < check_out:
                if hotel_room.is_booked(date):
                    messages.error(request, f'The room is already booked on {date.strftime("%d-%m-%Y")}')
                    break
                date += timedelta(days=1)
            else:
                Booking.objects.create(room=hotel_room, start_date=check_in, end_date=check_out - timedelta(days=1))
                messages.success(request, 'Room booked successfully!')

                return redirect(f'/hotels/rooms/{hotel_room.id}/')
    else:
        # For GET requests or invalid POST requests, create an empty form
        form = BookRoomForm()

    messages.error(request, 'Booking failed!')
    return render(request, 'hotels/room_detail.html', {
        'title': 'Book Room',
        'hotel_room': hotel_room,
        'availability_calendar': availability_calendar,
        'booking_form': form
        })


@login_required
def submit_rating(request, hotel_id):
    hotel = Hotel.objects.get(id=hotel_id)
    ratings = hotel.ratings.all().order_by('-created_at')
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.hotel = Hotel.objects.get(id=hotel_id)
            rating.user = request.user
            rating.save()

            messages.success(request, 'Rating submited!')
            return redirect(f'/hotels/{hotel_id}/')
    else:
        form = RatingForm()
   
    messages.error(request, 'Rating submission error: Please rate between 1-5.')
    return render(request, 'hotels/hotel_detail.html', {
        'title': 'Rate Hotel',
        'hotel': hotel,
        'rating_form': form,
        'ratings': ratings,
    })

hotels/templates/hotels/book_room.html
<div  class="w-11/12 mx-auto mb-10 p-4 flex flex-col items-center md:flex-row md:justify-evenly md:items-center bg-slate-800 rounded-xl shadow-2xl">

    <form method="post" action="/hotels/rooms/{{hotel_room.id}}/book-room/" class="p-4 w-4/5 sm:w-2/3 md:w-1/3">
        {% csrf_token %}

        <div class="mb-2">
            <label class="inline-block mb-3">Check-in date:</label><br>
            {{ booking_form.start_date }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Check-out date:</label><br>
            {{ booking_form.end_date }}
        </div>

        <!-- {{ booking_form.as_p }} -->

        {% if booking_form.errors or booking_form.non_field_errors %}
        <div class="mb-2 p-6 bg-red-300 text-gray-800 rounded-xl">  
            {% for field in booking_form %}
                {{ field.errors }}
            {% endfor %}

            {{ booking_form.non_field_errors }}
        </div>  
        {% endif %} 

        <div class="mt-5 flex justify-center items-center">
            <button class="inline-block text-center px-3  py-1 text-md bg-emerald-600 rounded-xl shadow-2xl hover:bg-emerald-700 transition ease-in-out duration-300">Book Now</button>
        </div>
    </form>

    <!-- This presumes that 'availability' is a list of tuples (date, is_available) sorted by date -->
    <div>
        <table id="calendar">
            <thead>
            <tr>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wed</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
                <th>Sun</th>
            </tr>
            </thead>
            <tbody>
            {% for week, days in availability_calendar.items %}
                <tr>
                {% for day_info in days %}
                    {% if day_info %}
                    <td class="{{ day_info.1|lower }}">{{ day_info.0 }}</td>
                    {% else %}
                    <td class="empty">&nbsp;</td> <!-- Empty cell for padding -->
                    {% endif %}
                {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

hotels/templates/hotels/hotel_list.html
{% extends "core/base.html" %}

{% load static hotelextras %}


{% block title %}{{ title }}{% endblock %}


{% block style %}
<style>
    .checkbox-button input[type='checkbox'] {
        display: none;
    }
    
    .checkbox-button label {
        display: inline-block;
        width: 100%;
        margin: 5px;
        background-color: rgb(75 85 99);
        color: #ffffff;
        padding: 5px 10px;
        border-radius: 15px;
        cursor: pointer;
        transition: background-color 0.2s, color 0.2s;
    }

    .checkbox-button label.location_types:hover {
        background-color: rgb(31 41 55);
    }

    .checkbox-button label.amenities:hover {
        background-color: rgb(17 24 39);
    }
    
    
    .checkbox-button input[type='checkbox']:checked + label.location_types {
        background-color: rgb(31 41 55);
    }

    .checkbox-button input[type='checkbox']:checked + label.amenities {
        background-color: rgb(17 24 39);
    }
</style>
    
{% endblock %}


{% block content %}
<h2 class="mb-8 text-center text-2xl font-semibold">Hotels</h2>

<!-- {{ hotel_filter_form.location_types }} -->
<form id="location_types_filter" action="." method="get" class="mb-4">
    <div class="checkbox-button flex flex-wrap gap-3 justify-center mx-auto px-5 overflow-x-auto rounded-xl">
        {% for choice in hotel_filter_form.location_types %}
            <div>
                {{ choice.tag }}
                <label for="id_location_types_{{forloop.counter0}}" class="text-center location_types">{{ choice.choice_label }}</label>
            </div>
        {% endfor %}
    </div>
</form>

<div class="w-max mx-auto p-4 md:hidden">
    <button id="filterToggle" class="py-2 px-10 bg-gray-600 text-white rounded-lg hover:bg-gray-800 transition ease-in-out duration-300" onclick="toggleFilter()">Filters</button>
</div>

<div class="flex flex-col md:flex-row h-screen gap-4">

    <div id="filter" class="hidden md:block md:w-1/4 p-4 bg-slate-800 md:flex flex-col justify-start items-center rounded-xl shadow-2xl transition-transform duration-300 ease-in-out">
        <!-- Filter Content Goes Here -->
        <h1 class="text-center text-xl mt-4 mb-6">Filter</h1>

        <form id="amenities_filter" method="get" action="." class="mb-4">
            <input name="query" value="{{query}}" type="text" class="w-full mb-8 py-1 px-4 bg-slate-700 border border-2 border-gray-950 rounded-xl" placeholder="Search your hotel">

            <!-- {{ hotel_filter_form.amenities }} -->
            <h1 class="mb-4 text-lg font-semibold">Amenities:</h1>

            <div class="checkbox-button flex flex-row flex-wrap md:flex-col items-center gap-2 rounded-lg">
                {% for amenity in hotel_filter_form.amenities %}
                    <div class="md:w-4/5">
                        {{ amenity.tag }}
                        <label for="id_amenities_{{forloop.counter0}}" class="text-center amenities">{{ amenity.choice_label }}</label>
                    </div>
                {% endfor %}
            </div>
        </form>

        <hr class="w-full mb-4">

        <a href="{% url 'hotels:hotels' %}" class="mb-4 py-1 px-3 bg-emerald-600 rounded-lg hover:bg-emerald-700 transition ease-in-out duration-300">Clear Filter</a>
    </div>

    <div id="hotel_list" class="w-full md:w-3/4 mx-auto flex flex-col gap-4 overflow-y-auto rounded-xl">
        {% for hotel in hotels %}
            <div id="hotel_{{ forloop.counter0 }}" class="p-4 rounded-xl bg-slate-800 flex flex-col md:flex-row justify-center items-center gap-4 shadow-lg">
                
                {% with hotel.images.all as images %}
                {% if images %}
                <div id="hotel_{{ forloop.counter0 }}_image" class="w-full h-80 md:w-1/2 md:h-full lg:w-2/5 bg-white rounded-lg overflow-hidden">
                    <img src="{{ images.0.image.url }}" alt="{{hotel.hotel_name}}" class="w-full h-full object-cover">
                </div>
                {% else %}
                <div id="hotel_{{ forloop.counter0 }}_image" class="w-2/5 h-60 bg-gray-800 rounded-lg flex items-center justify-center">
                    <span class="text-gray-500">No image available</span>
                </div>
                {% endif %}
                {% endwith %}

                <div id="hotel_{{ forloop.counter0 }}_detail" class="w-full h-max md:w-1/2 lg:w-3/5 p-2 flex flex-col justify-start bg-slate-700 rounded-xl">

                    <div class="w-full p-4 text-2xl font-semibold">{{ hotel.hotel_name }}</div>
                
                    <p class="w-full py-2 px-5 text-lg">Deals starting from ${{ hotel.get_lowest_room_price }}</p>

                    <p class="w-full py-2 px-5 text-lg">Location : {{ hotel.location }}</p>

                    <p class="w-full py-2 px-5 text-lg">Rating : {{ hotel.get_average_rating|stars|safe }}</p>

                    <div class="w-full py-2 px-5 flex justify-center items-center">
                        <a href="{% url 'hotels:hotel-detail' hotel.id %}" class="mt-2 inline-block py-2 px-6 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition ease-in-out duration-300">View Deals</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    function toggleFilter() {
        var filterElement = document.getElementById('filter');
        if (filterElement.classList.contains('hidden')) {
        filterElement.classList.remove('hidden');
        filterElement.classList.add('flex');
        } else {
        filterElement.classList.add('hidden');
        filterElement.classList.remove('flex');
        }
    }
</script>
{% endblock %}

hotels/templates/hotels/room_detail.html
{% extends 'core/base.html' %}
{% load static %}


{% block title %}{{ title }}{% endblock %}


{% block style %}
<style>

    .slide {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      opacity: 0; /* Make slides invisible */
      transition: opacity 0.5s ease-in-out; /* Smooth transition for fade in/out */
    }

    #calendar {
    border-collapse: separate;
    border-spacing: 5px; /* adjust the value as needed */
    }

    #calendar td {
        height: 35px;
        width: 35px;
        border-radius: 8px;
        text-align: center;
    }

    #calendar td.available {
        background-color: rgb(5 150 105); /* Light green for available days */
    }

    #calendar td.booked {
        background-color: rgb(190 18 60); /* Light red for booked days */
    }

    #calendar td.empty {
        background-color: rgb(75 85 99); /* Light grey for empty cells */
    }

</style>
{% endblock %}


{% block content %}
<div class="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8">

    <h1 class="text-center text-2xl font-semibold">{{hotel_room.get_room_type_display}} Room</h1>

    <!-- Sliding photos section -->
    <div class="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <!-- Slider -->
        <div id="slider" class="h-[350px] md:h-[450px] flex overflow-hidden shadow-2xl relative rounded-xl border-8 border-slate-900">
            <!-- Foreach loop for displaying hotel images -->
            {% if hotel_room.images.all %}
                {% for image in hotel_room.images.all %}
                <div class="slide min-w-full flex-shrink-0">
                    <img src="{{ image.image.url }}" class="w-full h-full object-cover" alt="{{ hotel_room.room_number }}">
                </div>
                {% endfor %}
            {% else %}
                <div class="w-full bg-gray-800 rounded-lg flex items-center justify-center">
                    <span class="text-gray-500">No image available</span>
                </div>
            {% endif %}
        </div>
        <!-- Dots container -->
        <div class="dots-container flex justify-center p-4">
            {% for image in hotel_room.images.all %}
            <span class="dot cursor-pointer rounded-full h-3 w-3 mx-1 mb-1 bg-white inline-block"></span>
            {% endfor %}
        </div>
    </div>

    <hr class="w-3/5 mx-auto border-4 rounded-full border-slate-800">

    <h1 class="mt-6 mb-6 text-center text-2xl font-semibold">Room Details</h1>

    {% include 'hotels/room_info.html' %}

    <hr class="w-3/5 mx-auto border-4 rounded-full border-slate-800">

    <h1 class="mt-6 mb-6 text-center text-2xl font-semibold">Book Room</h1>
        
    {% include 'hotels/book_room.html' %}

    

</div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'js/slideshow.js' %}"></script>
{% endblock %}

hotels/templates/hotels/room_info.html
<div  class="w-11/12 mx-auto mb-10 p-8 flex flex-col justify-start gap-5 bg-slate-800 rounded-xl shadow-2xl">

    <h2 class="font-semibold">Room No : {{ hotel_room.room_number }}</h2>

    <h2 class="font-semibold">Room Type : {{ hotel_room.get_room_type_display }} Room</h2>

    <p><span class="font-semibold">Description :</span> <br>{{ hotel_room.description }}</p>

</div>

hotels/templates/hotels/room_list.html
<div class="w-11/12 mx-auto mb-10 flex flex-col gap-4 overflow-y-auto rounded-xl">
    <!-- Repeat this block for each room -->
    {% for room in hotel.rooms.all %}
    <div class="bg-slate-800 flex flex-col md:flex-row gap-4 p-4 rounded-xl shadow-lg">

        {% with room.images.all as images %}
        {% if images %}
        <div class="w-full h-80 md:w-1/3 md:h-60 bg-white rounded-lg overflow-hidden">
            <img src="{{ images.0.image.url }}" alt="{{ room.room_number }}" class="w-full h-full object-cover">
        </div>
        {% else %}
        <div class="w-full h-80 md:w-1/3 md:h-60 bg-gray-800 rounded-lg flex items-center justify-center">
            <span class="text-gray-500">No image available</span>
        </div>
        {% endif %}
        {% endwith %}

        <div class="w-full md:w-2/3 p-2 flex flex-col justify-start md:justify-around bg-gray-700 rounded-xl">

            <div class="px-4 py-2">
                <h3 class="text-2xl font-bold text-gray-300">{{ room.get_room_type_display }} Room</h3>
            </div>

            <div class="px-4 py-2">
                <h3 class="text-xl font-semibold text-gray-400">Room Number {{ room.room_number }}</h3>
            </div>

            <div class="px-4 py-2">
                <p class="text-emerald-500">Price: {{ room.price }}</p>
            </div>

            <div class="px-4 py-2">
                <a href="{% url 'hotels:hotel-room-detail' room.id %}" class="inline-block py-1 px-3 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition ease-in-out duration-300">
                    Details
                </a>
            </div>

        </div>
    </div>
    {% endfor %}
</div>